### ISSUE TITLE
Is example website still working correctly?

### ISSUE THREAD

**Issue by Ryan-Willpower** [abhiprojectz/motionia#1] opened 2020-06-04 09:12 UTC
Hi, I just curious why is the example website is unable to click.

<img width="1440" alt="Screen Shot 2563-06-04 at 16 09 30" src="https://user-images.githubusercontent.com/30806319/83738161-20868b80-a67e-11ea-88e1-c8d3e9f453f3.png">

Is it a bug?

**Comment by abhiprojectz** [comment] 2020-06-04 11:14
Its working correctly , i just checked it. However, i'm updating all the anims and adding some more demos too. Just check it now twicely , then do comment whether now its working correctly?

**Comment by anantajitjg** [comment] 2020-06-04 11:53
The examples are not working for me too. Tested in Both Firefox and Chrome.

**Comment by hansfpc** [comment] 2020-06-04 13:50
The examples are not working for me too :c

**Comment by abhiprojectz** [comment] 2020-06-04 15:37
Thanks for the issue.The issue is now fixed there was a error in jsdevlir don't targetting to the updated file of motionia.js just add @latest to the repo name in script path , if you encounter such error in future thanks.

**Closed by abhiprojectz** 2020-06-04 15:37 UTC
